version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: biometec-postgres
    restart: "no"
    environment:
      POSTGRES_DB: mesacontrol_db
      POSTGRES_USER: admin_biometec
      POSTGRES_PASSWORD: admin_password
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: