-- ============================================================
-- DDL: Esquema Inicial MVP Mesa de Control
-- ============================================================

CREATE TABLE usuario (
                         id SERIAL PRIMARY KEY,
                         nombre VARCHAR(255) NOT NULL,
                         email VARCHAR(255) UNIQUE NOT NULL,
                         password VARCHAR(255) NOT NULL,
                         rol VARCHAR(50) NOT NULL,
                         activo BOOLEAN DEFAULT TRUE
);

CREATE TABLE cliente (
                         id SERIAL PRIMARY KEY,
                         nombre TEXT NOT NULL,
                         ubicacion TEXT NOT NULL
);

CREATE TABLE equipo (
                        id SERIAL PRIMARY KEY,
                        cliente_id INTEGER NOT NULL REFERENCES cliente(id),
                        nombre_equipo TEXT NOT NULL,
                        marca TEXT NOT NULL,
                        modelo TEXT NOT NULL,
                        numero_serie TEXT NOT NULL
);

CREATE TABLE ticket (
                        id SERIAL PRIMARY KEY,
                        folio VARCHAR(50) UNIQUE NOT NULL,
                        tipo VARCHAR(50) NOT NULL,
                        prioridad INTEGER NOT NULL,
                        estado VARCHAR(50) NOT NULL,
                        descripcion_inicial TEXT NOT NULL,
                        fecha_creacion TIMESTAMP NOT NULL,
                        fecha_vencimiento_sla TIMESTAMP NOT NULL,
                        fecha_cierre TIMESTAMP,
                        folio_cotizacion VARCHAR(100),
                        folio_orden_servicio VARCHAR(100),
                        cliente_id INTEGER NOT NULL REFERENCES cliente(id),
                        equipo_id INTEGER NOT NULL REFERENCES equipo(id),
                        responsable_id INTEGER REFERENCES usuario(id)
);

CREATE TABLE comentario (
                            id SERIAL PRIMARY KEY,
                            ticket_id INTEGER NOT NULL REFERENCES ticket(id),
                            autor_id INTEGER NOT NULL REFERENCES usuario(id),
                            comentario TEXT NOT NULL,
                            fecha_creacion TIMESTAMP NOT NULL
);

-- ============================================================
-- DML: Carga de Catálogos (Clientes y Equipos)
-- ============================================================

-- Clientes
-- ... (Para mantener la legibilidad, inserta aquí el resto de tus 74 registros de clientes asegurándote de usar "INSERT INTO cliente (id, nombre, ubicacion)") ...
INSERT INTO cliente (id, nombre, ubicacion) VALUES (1, 'HOSPITAL CHIAPAS NOS UNE DR. JESUS GILBERTO GOMEZ MAZA CSIMB006533', 'BOULEVARD CENTENARIO DEL EJERCITO MEXICANO 1913-2013, SIN NÚMERO, FRACCIONAMIENTO LAS TORRES, CP. 29045, MUNICIPIO TUXTLA GUTIERREZ, CHIAPAS');
INSERT INTO cliente (id, nombre, ubicacion) VALUES (2, 'CENTRO MÉDICO LIC. ADOLFO LÓPEZ MATEOS MCIMB009145', 'AVENIDA DR. NICOLAS SAN JUAN , SIN NÚMERO, COLONIA LA MAGDALENA, CP. 50010, MUNICIPIO TOLUCA, MEXICO');
INSERT INTO cliente (id, nombre, ubicacion) VALUES (3, 'CENTRO DE ALTA ESPECIALIDAD DR. RAFAEL LUCIO VZIMB002330', 'AVENIDA ADOLFO RUIZ CORTINES, No. 2903, COLONIA UNIDAD MAGISTERIAL, CP. 91020, MUNICIPIO XALAPA, VERACRUZ DE IGNACIO DE LA LLAVE');
INSERT INTO cliente (id, nombre, ubicacion) VALUES (4, 'HOSPITAL REGIONAL DE XALAPA DR. LUIS F. NACHÓN VZIMB002342', 'CALLE PEDRO RENDON, No. 1, COLONIA CENTRO, CP. 91000, MUNICIPIO XALAPA, VERACRUZ DE IGNACIO DE LA LLAVE');
INSERT INTO cliente (id, nombre, ubicacion) VALUES (5, 'HOSPITAL GENERAL DE APAN HGIMB004800', 'LIBRAMIENTO JOSÉ FRANCISCO OSORNO, No. 2, COLONIA SAN RAFAEL, CP. 43909, MUNICIPIO APAN, HIDALGO');
INSERT INTO cliente (id, nombre, ubicacion) VALUES (6, 'C.S.T-III BEATRIZ VELASCO DE ALEMÁN. DFIMB002242', 'CALLE ING. EDUARDO MOLINA ESQUINA PELUQUEROS, SIN NÚMERO, COLONIA 20 DE NOVIEMBRE (LA MICHOACÁNA), CP. 15240, MUNICIPIO VENUSTIANO CARRANZA, CIUDAD DE MEXICO');
INSERT INTO cliente (id, nombre, ubicacion) VALUES (7, 'C.S.T-III CUAJIMALPA DFIMB000405', 'CERRADA DE JUAREZ, No. 11A, COLONIA CUAJIMALPA, CP. 05000, MUNICIPIO CUAJIMALPA DE MORELOS, CIUDAD DE MEXICO');
INSERT INTO cliente (id, nombre, ubicacion) VALUES (8, 'C.S.T-III DR GASTÓN MELO DFIMB001250', 'CALLE GASTÓN MELO, SIN NÚMERO, PUEBLO SAN ANTONIO TECOMITL, CP. 12100, MUNICIPIO MILPA ALTA, CIUDAD DE MEXICO');
INSERT INTO cliente (id, nombre, ubicacion) VALUES (9, 'C.S.T-III DR. GALO SOBERÓN Y PARRA DFIMB000171', 'CALZADA CAMARONES, No. 485, COLONIA SINDICATO MEXICANO DE ELECTRICISTAS, CP. 02060, MUNICIPIO AZCAPOTZALCO, CIUDAD DE MEXICO');
INSERT INTO cliente (id, nombre, ubicacion) VALUES (10, 'C.S.T-III DR. GUILLERMO ROMAN Y CARRILLO DFIMB000970', 'AVENIDA ZACATLÁN, No. 146, PUEBLO SAN LORENZO TEZONCO, CP. 09790, MUNICIPIO IZTAPALAPA, CIUDAD DE MEXICO');
INSERT INTO cliente (id, nombre, ubicacion) VALUES (11, 'C.S.T-III DR. JOSÉ MA. RODRÍGUEZ DFIMB001974', 'CALLE SAN ANTONIO ABAD, No. 350, COLONIA ASTURIAS, CP. 06850, MUNICIPIO CUAUHTEMOC, CIUDAD DE MEXICO');
INSERT INTO cliente (id, nombre, ubicacion) VALUES (12, 'C.S.T-III DR. JOSÉ ZOZAYA DFIMB000813', 'CALLE CORREGIDORA, No. 135, COLONIA SANTA ANITA, CP. 08300, MUNICIPIO IZTACALCO, CIUDAD DE MEXICO');
INSERT INTO cliente (id, nombre, ubicacion) VALUES (13, 'C.S.T-III DR. RAFAEL RAMÍREZ SUÁREZ DFIMB000714', 'CALLE MONTEVIDEO ESQUINA 17 DE MAYO, No. 555, COLONIA SAN BARTOLO ATEPEHUACAN, CP. 07730, MUNICIPIO GUSTAVO A. MADERO, CIUDAD DE MEXICO');
INSERT INTO cliente (id, nombre, ubicacion) VALUES (14, 'C.S.T-III DRA. MARGARITA CHORNE Y SALAZAR DFIMB000282', 'AVENIDA DIVISIÓN DEL NORTE, No. 2986, COLONIA ATLÁNTIDA, CP. 04370, MUNICIPIO COYOACAN, CIUDAD DE MEXICO');
INSERT INTO cliente (id, nombre, ubicacion) VALUES (15, 'C.S.T-III MÉXICO-ESPAÑA DFIMB002061', 'CALLE LAGO ISEO, No. 128, COLONIA MARIANO ESCOBEDO, CP. 11310, MUNICIPIO MIGUEL HIDALGO, CIUDAD DE MEXICO');
INSERT INTO cliente (id, nombre, ubicacion) VALUES (16, 'C.S.T-III MIGUEL HIDALGO DFIMB001472', 'CALLE FIDELIO (ANTES LIVIO ESPINOSA FRÍAS) ENTRE CENICIENTA Y DEODATO, No. 4, COLONIA MIGUEL HIDALGO, CP. 13200, MUNICIPIO TLAHUAC, CIUDAD DE MEXICO');
INSERT INTO cliente (id, nombre, ubicacion) VALUES (17, 'C.S.T-III OASIS DFIMB002580', 'CALLE SAN JERÓNIMO, No. 2625, COLONIA SAN BERNABÉ OCOTEPEC, CP. 10300, MUNICIPIO LA MAGDALENA CONTRERAS, CIUDAD DE MEXICO');
INSERT INTO cliente (id, nombre, ubicacion) VALUES (18, 'C.S.T-III TULYEHUALCO DFIMB001805', 'AVENIDA TLAHUAC-TULYEHUALCO ENTRE TAPIA Y DIVISIÓN DEL NORTE, MANZANA 324 LOTE 2 ZONA 357, COLONIA BARRIO SAN SEBASTIÁN TULYEHUALCO, CP. 16730, MUNICIPIO XOCHIMILCO, CIUDAD DE MEXICO');
INSERT INTO cliente (id, nombre, ubicacion) VALUES (19, 'HOSPITAL MATERNO INFANTIL DR. NICOLÁS M. CEDILLO DFIMB000031', 'CALLE GUSTAVO J., SIN NÚMERO, UNIDAD FRANCISCO VILLA, CP. 02400, MUNICIPIO AZCAPOTZALCO, CIUDAD DE MEXICO');
INSERT INTO cliente (id, nombre, ubicacion) VALUES (20, 'H.G. DR. NICOLÁS SAN JUAN MCIMB006946', 'AVENIDA DR. NICOLÁS SAN JUAN, SIN NÚMERO, COLONIA LA MAGDALENA, CP. 50010, MUNICIPIO TOLUCA, MEXICO');
INSERT INTO cliente (id, nombre, ubicacion) VALUES (21, 'HOSPITAL GENERAL DE AXAPUSCO MCIMB009775', 'AVENIDA BENITO JUÁREZ, SIN NÚMERO, BARRIO AXAPUSCO, CP. 55940, MUNICIPIO AXAPUSCO, MEXICO');
INSERT INTO cliente (id, nombre, ubicacion) VALUES (22, 'UNIDAD DE ESPECIALIDAD MEDICA DETECCIÓN Y DIAGNÓSTICO DEL CANCER DE MAMA HUIXQUILUCAN MCIMB009302', 'CALLE AGUSTÍN MELGAR, No. 29, BARRIO BARRIO SAN JUAN BAUTISTA, CP. 52760, MUNICIPIO HUIXQUILUCAN, MEXICO');
INSERT INTO cliente (id, nombre, ubicacion) VALUES (23, 'HG OAXACA DR. AURELIO VALDIVIESO OCIMB000881', 'CALLE PROFIRIO DIAZ, No. 410, COLONIA REFORMA, CP. 68025, MUNICIPIO OAXACA DE JUAREZ, OAXACA');
INSERT INTO cliente (id, nombre, ubicacion) VALUES (24, 'TAMAZUNCHALE SPIMB003006', 'CALLE FELIPE ANGELES, SIN NÚMERO, COLONIA REVOLUCION SECTOR IXTLAPALACO, CP. 79960, MUNICIPIO TAMAZUNCHALE, SAN LUIS POTOSI');
INSERT INTO cliente (id, nombre, ubicacion) VALUES (25, 'CLINICA DE LA MUJER Y PARTO HUMANIZADO CSIMB003955', 'CARRETERA HUIXTLA-VILLA COMALTITLAN KM. 0.5, SIN NÚMERO, COLONIA EL ESPEJO, C.P. 30640, MUNICIPIO HUIXTLA, CHIAPAS');
INSERT INTO cliente (id, nombre, ubicacion) VALUES (26, 'CLINICA PARA LA ATENCION DE PARTO HUMANIZADO SAN CRISTOBAL DE LAS CASAS CSIMB003902', 'CALLE LAGUNA DE PATZCUARO, SIN NÚMERO, BARRIO MARIA AUXILIADORA, C.P. 29290, MUNICIPIO SAN CRISTOBAL DE LAS CASAS, CHIAPAS');
INSERT INTO cliente (id, nombre, ubicacion) VALUES (27, 'H. B. C. DE FRONTERA COMALAPA CSIMB005524', 'CARRETERA FRONTERA COMALAPA-PASO HONDO, SIN NÚMERO, BARRIO VISTA HERMOSA, C.P. 30140, MUNICIPIO FRONTERA COMALAPA, CHIAPAS');
INSERT INTO cliente (id, nombre, ubicacion) VALUES (28, 'HOSPITAL GENERAL MARÍA IGNACIA GANDULFO COMITAN CSIMB000460', 'CALLE 9A. SUR ORIENTE, No. 11, BARRIO SAN SEBASTIÁN, CP. 30029, MUNICIPIO COMITAN DE DOMINGUEZ, CHIAPAS');
INSERT INTO cliente (id, nombre, ubicacion) VALUES (29, 'HOSPITAL GENERAL PALENQUE CSIMB001732', 'AVENIDA PROLONGACION JUÁREZ, SIN NÚMERO, COLONIA NANDIUME, C.P. 29960, MUNICIPIO PALENQUE, CHIAPAS');
INSERT INTO cliente (id, nombre, ubicacion) VALUES (30, 'HOSPITAL GENERAL PICHUCALCO CSIMB001884', 'CALLE PONCIANO ROJAS, SIN NÚMERO, FRACCIONAMIENTO LAS PALMERAS, C.P. 29520, MUNICIPIO PICHUCALCO, CHIAPAS');
INSERT INTO cliente (id, nombre, ubicacion) VALUES (31, 'HOSPITAL REGIONAL DR. RAFAEL PASCASIO GAMBOA TUXTLA CSIMB002980', 'AVENIDA 9A. SUR, SIN NÚMERO, BARRIO SAN FRANCISCO, CP. 29066, MUNICIPIO TUXTLA GUTIERREZ, CHIAPAS');
INSERT INTO cliente (id, nombre, ubicacion) VALUES (32, 'MOTOZINTLA DE MENDOZA CSIMB001435', 'AVENIDA 4A. NORTE, No. 733, BARRIO EMILIANO ZAPATA, C.P. 30900, MUNICIPIO MOTOZINTLA, CHIAPAS');
INSERT INTO cliente (id, nombre, ubicacion) VALUES (33, 'HOSPITAL GENERAL DE TULANCINGO HGIMB005005', 'AVENIDA MÉXICO, No. 47, COLONIA PAXTEPEC, CP. 43767, MUNICIPIO SANTIAGO TULANTEPEC DE LUGO GUERRERO, HIDALGO');
INSERT INTO cliente (id, nombre, ubicacion) VALUES (34, 'HOSPITAL GENERAL TULA HGIMB004824', 'CARRETERA TULA - TEPEJI KM. 1.5, SIN NÚMERO, COLONIA EL CARMEN, CP. 42830, MUNICIPIO TULA DE ALLENDE, HIDALGO');
INSERT INTO cliente (id, nombre, ubicacion) VALUES (35, 'H.G. DR. JOSÉ MARÍA RODRÍGUEZ MCIMB002005', 'AVENIDA LEONA VICARIO, SIN NÚMERO, FRACCIONAMIENTO VALLE DE ANAHUAC SECCION A, CP. 55210, MUNICIPIO ECATEPEC DE MORELOS, MEXICO');
INSERT INTO cliente (id, nombre, ubicacion) VALUES (36, 'HOSPITAL DE LAS CULTURAS SAN CRISTOBAL DE LAS CASAS CSIMB005500', 'BOULEVARD JAVIER LÓPEZ MORENO, SIN NÚMERO, BARRIO FÁTIMA, CP. 29264, MUNICIPIO SAN CRISTOBAL DE LAS CASAS, CHIAPAS');
INSERT INTO cliente (id, nombre, ubicacion) VALUES (37, 'HOSPITAL GENERAL TAPACHULA CSIMB003680', 'KM 10.5 DE LA CARRETERA FEDERAL TAPACHULA- PUERTO MADERO, SIN NÚMERO, FRACCIONAMIENTO SANTA TERESA, CP. 30825, MUNICIPIO TAPACHULA, CHIAPAS');
INSERT INTO cliente (id, nombre, ubicacion) VALUES (38, 'HOSPITAL GENERAL DE TICOMÁN DFIMB000446', 'CALLE PLAN DE SAN LUIS, SIN NÚMERO, COLONIA SANTA MARÍA TICOMÁN, CP. 07330, MUNICIPIO GUSTAVO A. MADERO, CIUDAD DE MEXICO');
INSERT INTO cliente (id, nombre, ubicacion) VALUES (39, 'HOSPITAL GENERAL ATLACOMULCO MCIMB009063', 'BOULEVARD JORGE JIMENEZ CANTÚ, SIN NÚMERO, COLONIA MERCEDES, CP. 50454, MUNICIPIO ATLACOMULCO, MEXICO');
INSERT INTO cliente (id, nombre, ubicacion) VALUES (40, 'HOSPITAL GENERAL DE CHALCO MCIMB001515', 'BOULEVARD CUAUHTÉMOC PONIENTE, SIN NÚMERO, COLONIA LA BOMBA, CP. 56600, MUNICIPIO CHALCO, MEXICO');
INSERT INTO cliente (id, nombre, ubicacion) VALUES (41, 'HOSPITAL GENERAL TEHUACAN PLIMB002516', 'CALLE 19 PONIENTE, No. 3800, COLONIA EL RIEGO, CP. 75763, MUNICIPIO TEHUACAN, PUEBLA');
INSERT INTO cliente (id, nombre, ubicacion) VALUES (42, 'HOSPITAL REGIONAL DE ALTA ESPECIALIDAD EN CD VICTORIA BICENTENARIO 2010 TSIMB002865', 'LIBRAMIENTO GUADALUPE VICTORIA, SIN NÚMERO, COLONIA AREA DE PAJARITOS, CP. 87087, MUNICIPIO VICTORIA, TAMAULIPAS');
INSERT INTO cliente (id, nombre, ubicacion) VALUES (43, 'HOSPITAL GENERAL XOCO DFIMB001822', 'CALLE MÉXICO COYOACÁN, SIN NÚMERO, COLONIA GENERAL PEDRO MARÍA ANAYA, CP. 03340, MUNICIPIO BENITO JUAREZ, CIUDAD DE MEXICO');
INSERT INTO cliente (id, nombre, ubicacion) VALUES (44, 'HOSPITAL DEL NIÑO MORELENSE MSIMB002235', 'AVENIDA DE LA SALUD, No. 1, COLONIA BENITO JUÁREZ, CP. 62765, MUNICIPIO EMILIANO ZAPATA, MORELOS');
INSERT INTO cliente (id, nombre, ubicacion) VALUES (45, 'HOSPITAL REGIONAL DE ALTA ESPECIALIDAD DR.IGNACIO MORONES PRIETO SPIMB002574', 'CALLE VENUSTIANO CARRANZA, No. 2395 BIS, COLONIA UNVERSITARIA, CP. 78290, MUNICIPIO SAN LUIS POTOSI, SAN LUIS POTOSI');
INSERT INTO cliente (id, nombre, ubicacion) VALUES (46, 'HOSPITAL GENERAL LAS AMÉRICAS MCIMB009203', 'AVENIDA SIMÓN BOLÍVAR, SIN NÚMERO, FRACCIONAMIENTO LAS AMERICAS, CP. 55076, MUNICIPIO ECATEPEC DE MORELOS, MEXICO');
INSERT INTO cliente (id, nombre, ubicacion) VALUES (47, 'HOSPITAL DE ESPECIALIDADES PEDIÁTRICAS CSIMB003511', 'BOULEVARD SS JUAN PABLO II, SIN NÚMERO, COLONIA CASTILLO TIELMANS, CP. 29070, MUNICIPIO TUXTLA GUTIERREZ, CHIAPAS');
INSERT INTO cliente (id, nombre, ubicacion) VALUES (48, 'HOSPITAL REGIONAL DE ALTA ESPECIALIDAD DE OAXACA OCIMB006826', 'CALLE ALDAMA, SIN NÚMERO, COLONIA NO ESPECÍFICADA, CP. 71294, MUNICIPIO SAN BARTOLO COYOTEPEC, OAXACA');
INSERT INTO cliente (id, nombre, ubicacion) VALUES (49, 'HOSPITAL GENERAL DR EDUARDO VAZQUEZ N PLIMB001780', 'CALLE ANTIGUO CAMINO A GUADALUPE HIDALGO, No. 11350, UNIDAD HABITACIONAL INFONAVIT AGUA SANTA, CP. 72490, MUNICIPIO PUEBLA, PUEBLA');
INSERT INTO cliente (id, nombre, ubicacion) VALUES (50, 'HOSPITAL GENERAL DE ESPECIALIDADES DR. JAVIER BUENFIL OSORIO CCIMB001526', 'CALLE LÁZARO CÁRDENAS PROLONGACIÓN ANTIGUA CALLE A CHINA Y AVENIDA LÓPEZ PORTILLO, No. 208, COLONIA LAS FLORES, CP. 24097, MUNICIPIO CAMPECHE, CAMPECHE');
INSERT INTO cliente (id, nombre, ubicacion) VALUES (51, 'HOSPITAL GENERAL DE CULIACÁN SLIMB000014', 'BOULEVARD PASEO DE TAMAZULA, SIN NÚMERO, COLONIA LA LIMITA DE ITAJE, CP. 80064, MUNICIPIO CULIACAN, SINALOA');
INSERT INTO cliente (id, nombre, ubicacion) VALUES (52, 'HOSPITAL REGIONAL DE ALTA ESPECIALIDAD DR. JUAN GRAHAM CASASUS TCIMB000791', 'CARRETERA VILLAHERMOSA-LA ISLA KM 1.5, SIN NÚMERO, COLONIA MIGUEL HIDALGO, CP. 86127, MUNICIPIO CENTRO, TABASCO');
INSERT INTO cliente (id, nombre, ubicacion) VALUES (53, 'HOSPITAL GENERAL TIJUANA BCIMB000734', 'AVENIDA CENTENARIO, No. 10851, COLONIA ZONA RÍO, CP. 22000, MUNICIPIO TIJUANA, BAJA CALIFORNIA');
INSERT INTO cliente (id, nombre, ubicacion) VALUES (54, 'HOSPITAL REGIONAL DE ALTA ESPECIALIDAD IXTAPALUCA MCIMB012295', 'CARRETERA FEDERAL MÉXICO-PUEBLA, No. KM. 34.5, COLONIA IXTAPALUCA, CP. 56530, MUNICIPIO IXTAPALUCA, MEXICO');
INSERT INTO cliente (id, nombre, ubicacion) VALUES (55, 'HOSPITAL DE ALTA ESPECIALIDAD DE VERACRUZ VZIMB005533', 'AVENIDA 20 DE NOVIEMBRE, No. 1074, COLONIA CENTRO, CP. 91700, MUNICIPIO VERACRUZ, VERACRUZ DE IGNACIO DE LA LLAVE');
INSERT INTO cliente (id, nombre, ubicacion) VALUES (56, 'HOSPITAL DE LA NIÑEZ POBLANA PLIMB005205', 'BOULEVARD DEL NIÑO POBLANO, No. 5307, COLONIA CONCEPCIÓN LA CRUZ, CP. 72836, MUNICIPIO SAN ANDRES CHOLULA, PUEBLA');
INSERT INTO cliente (id, nombre, ubicacion) VALUES (57, 'HOSPITAL GENERAL DE RÍOVERDE SPIMB000585', 'CALLE RIOVERDE - SAN CIRO DE ACOSTA, SIN NÚMERO, COLONIA CENTRO, CP. 79610, MUNICIPIO RIOVERDE, SAN LUIS POTOSI');
INSERT INTO cliente (id, nombre, ubicacion) VALUES (58, 'HOSPITAL GENERAL DE LA MUJER Y LA NIÑEZ OAXAQUEÑA OCIMB009631', 'CARRETERA OAXACA PUERTO ESCONDIDO KM 18, SIN NÚMERO, PUEBLO REYES MANTECON, CP. 71295, MUNICIPIO SAN BARTOLO COYOTEPEC, OAXACA');
INSERT INTO cliente (id, nombre, ubicacion) VALUES (59, 'HOSPITAL GENERAL TECAMACHALCO PLIMB007170', 'AVENIDA MIGUEL HIDALGO, No. 2423, COLONIA TECAMACHALCO CENTRO, CP. 75480, MUNICIPIO TECAMACHALCO, PUEBLA');
INSERT INTO cliente (id, nombre, ubicacion) VALUES (60, 'UNIDAD DE ESPECIALIDADES MÉDICAS DE IMAGENOLOGÍA DE VILLAHERMOSA TCIMB004945', 'AVENIDA CORONEL GREGORIO MENDEZ MAGAÑA, SIN NÚMERO, COLONIA ATASTA DE SERRA, CP. 86100, MUNICIPIO CENTRO, TABASCO');
INSERT INTO cliente (id, nombre, ubicacion) VALUES (61, 'HOSPITAL GENERAL AJUSCO MEDIO DFIMB002674', 'CALLE ENCINOS, No. 42, COLONIA AMPLIACIÓN MIGUEL HIDALGO 4TA SECCIÓN, CP. 14250, MUNICIPIO TLALPAN, CIUDAD DE MEXICO');
INSERT INTO cliente (id, nombre, ubicacion) VALUES (62, 'HOSPITAL GENERAL DR. RUBÉN LEÑERO DFIMB002020', 'CALLE PLAN DE SAN LUIS Y DÍAZ MIRÓN, SIN NÚMERO, COLONIA SANTO TOMÁS, CP. 11340, MUNICIPIO MIGUEL HIDALGO, CIUDAD DE MEXICO');
INSERT INTO cliente (id, nombre, ubicacion) VALUES (63, 'HOSPITAL PEDIÁTRICO DE SINALOA SLIMB002230', 'BOULEVARD CONSTITUCIÓN, SIN NÚMERO, COLONIA JORGE ALMADA, CP. 80200, MUNICIPIO CULIACAN, SINALOA');
INSERT INTO cliente (id, nombre, ubicacion) VALUES (64, 'HOSPITAL GENERAL DE MEXICALI BCIMB000355', 'CALLE DEL HOSPITAL, SIN NÚMERO, COLONIA CENTRO CÍVICO, CP. 21000, MUNICIPIO MEXICALI, BAJA CALIFORNIA');
INSERT INTO cliente (id, nombre, ubicacion) VALUES (65, 'HG SALINA CRUZ OCIMB008651', 'SIN NÚMERO, COLONIA GRANADILLO, CP. 70600, MUNICIPIO SALINA CRUZ, OAXACA');
INSERT INTO cliente (id, nombre, ubicacion) VALUES (66, 'HE DE LA NIÑEZ OAXAQUEÑA OCIMB001313', 'SIN NÚMERO, PUEBLO SAN BARTOLO, CP. 71256, MUNICIPIO SAN BARTOLO COYOTEPEC, OAXACA');
INSERT INTO cliente (id, nombre, ubicacion) VALUES (67, 'HG JUCHITAN DR. MACEDONIO BENITEZ FUENTES OCIMB007012', 'AVENIDA EFRAIN R GOMEZ, SIN NÚMERO, COLONIA SECCIÓN CUARTA, CP. 70000, MUNICIPIO HEROICA CIUDAD DE JUCHITAN DE ZARAGOZA, OAXACA');
INSERT INTO cliente (id, nombre, ubicacion) VALUES (68, 'HOSPITAL GENERAL DE SOLEDAD DE GRACIANO SÁNCHEZ SPIMB002970', 'CALLE VALENTIN AMADOR, No. 1112, COLONIA GENOVEVO RIVAS GUILLÉN, CP. 78436, MUNICIPIO SOLEDAD DE GRACIANO SANCHEZ, SAN LUIS POTOSI');
INSERT INTO cliente (id, nombre, ubicacion) VALUES (69, 'HOSPITAL GENERAL BICENTENARIO VILLAFLORES CSIMB005582', 'CARRETERA TUXTLA GUTIÉRREZ-VILLAFLORES KM. 87, SIN NÚMERO, RANCHO BELLAVISTA, CP. 30476, MUNICIPIO VILLAFLORES, CHIAPAS');
INSERT INTO cliente (id, nombre, ubicacion) VALUES (70, 'HOSP. GRAL. RENACIMIENTO GRIMB000024', 'CALLE JUAN E. ESCUDERO, No. 158, COLONIA RENACIMIENTO, CP. 39715, MUNICIPIO ACAPULCO DE JUAREZ, GUERRERO');
INSERT INTO cliente (id, nombre, ubicacion) VALUES (71, 'HOSPITAL GENERAL IXTAPAN DE LA SAL MCIMB009174', 'BOULEVARD IXTAPAN-TONATICO, SIN NÚMERO, COLONIA EL SALITRE, CP. 51900, MUNICIPIO IXTAPAN DE LA SAL, MEXICO');
INSERT INTO cliente (id, nombre, ubicacion) VALUES (72, 'HOSPITAL REGIONAL DE COATZACOALCOS DR.VALENTIN GÓMEZ FARIAS VZIMB000826', 'CALLE ZARAGOZA, No. 801, COLONIA CENTRO, CP. 96400, MUNICIPIO COATZACOALCOS, VERACRUZ DE IGNACIO DE LA LLAVE');
INSERT INTO cliente (id, nombre, ubicacion) VALUES (73, 'HOSPITAL GENERAL MILPA ALTA DFIMB001151', 'BOULEVARD NUEVO LEÓN, No. 386, COLONIA VILLA MILPA ALTA, CP. 12000, MUNICIPIO MILPA ALTA, CIUDAD DE MEXICO');
INSERT INTO cliente (id, nombre, ubicacion) VALUES (74, 'HOSPITAL GENERAL TOPILEJO DFIMB002341', 'AVENIDA SANTA CRUZ, No. 1, PUEBLO SAN MIGUEL TOPILEJO, CP. 14500, MUNICIPIO TLALPAN, CIUDAD DE MEXICO');
INSERT INTO cliente (id, nombre, ubicacion) VALUES (75, 'HOSPITAL DE LA MADRE Y EL NIÑO GUERRERENSE GRIMB008902', 'BOULEVARD RENE JUÁREZ CISNEROS, SIN NÚMERO, COLONIA CIUDAD DE LOS SERVICIOS, CP. 39074, MUNICIPIO CHILPANCINGO DE LOS BRAVO, GUERRERO');
INSERT INTO cliente (id, nombre, ubicacion) VALUES (76, 'HOSPITAL GENERAL OMETEPEC GRIMB005163', 'CARRETERA OMETEPEC-ACAPULCO KM. 2.5, SIN NÚMERO, OMETEPEC, CP. 41700, MUNICIPIO OMETEPEC, GUERRERO');

-- Equipos
-- ... (Inserta aquí el resto de tus 104 registros de equipos usando "INSERT INTO equipo") ...
INSERT INTO equipo (id, cliente_id, nombre_equipo, marca, modelo, numero_serie) VALUES (1, 1, 'ANGIOGRAFO ARCO BIPLANAR', 'SIEMENS', 'ARTIS ZEE', '1875');
INSERT INTO equipo (id, cliente_id, nombre_equipo, marca, modelo, numero_serie) VALUES (2, 2, 'ANGIOGRAFO ARCO MONOPLANAR', 'PHILIPS', 'ALLURA CV20', '164');
INSERT INTO equipo (id, cliente_id, nombre_equipo, marca, modelo, numero_serie) VALUES (3, 3, 'ANGIOGRAFO ARCO MONOPLANAR', 'PHILIPS', 'ALLURA XPER FD 20', '2084');
INSERT INTO equipo (id, cliente_id, nombre_equipo, marca, modelo, numero_serie) VALUES (4, 3, 'ANGIOGRAFO ARCO MONOPLANAR', 'PHILIPS', 'MULTIDIAGNOST ELEVA', '45');
INSERT INTO equipo (id, cliente_id, nombre_equipo, marca, modelo, numero_serie) VALUES (5, 4, 'ANGIOGRAFO ARCO MONOPLANAR', 'PHILIPS', 'ALLURA XPER FD10', '1200');
INSERT INTO equipo (id, cliente_id, nombre_equipo, marca, modelo, numero_serie) VALUES (6, 5, 'MASTOGRAFO DIGITAL', 'FUJIFILM', 'AMULET FELICIA', 'AMFL/0082/C1');
INSERT INTO equipo (id, cliente_id, nombre_equipo, marca, modelo, numero_serie) VALUES (7, 6, 'MASTOGRAFO DIGITAL', 'HOLOGIC', 'SELENIA DIMENSIONS', '19407089885');
INSERT INTO equipo (id, cliente_id, nombre_equipo, marca, modelo, numero_serie) VALUES (8, 7, 'MASTOGRAFO DIGITAL', 'HOLOGIC', 'SELENIA DIMENSIONS', '19407089879');
INSERT INTO equipo (id, cliente_id, nombre_equipo, marca, modelo, numero_serie) VALUES (9, 8, 'MASTOGRAFO DIGITAL', 'HOLOGIC', 'SELENIA DIMENSIONS', '19407089874');
INSERT INTO equipo (id, cliente_id, nombre_equipo, marca, modelo, numero_serie) VALUES (10, 9, 'MASTOGRAFO DIGITAL', 'HOLOGIC', 'SELENIA DIMENSIONS', '19407089868');
INSERT INTO equipo (id, cliente_id, nombre_equipo, marca, modelo, numero_serie) VALUES (11, 10, 'MASTOGRAFO DIGITAL', 'HOLOGIC', 'SELENIA DIMENSIONS', '19412100000000000');
INSERT INTO equipo (id, cliente_id, nombre_equipo, marca, modelo, numero_serie) VALUES (12, 11, 'MASTOGRAFO DIGITAL', 'HOLOGIC', 'SELENIA DIMENSIONS', '19407089876');
INSERT INTO equipo (id, cliente_id, nombre_equipo, marca, modelo, numero_serie) VALUES (13, 12, 'MASTOGRAFO DIGITAL', 'HOLOGIC', 'SELENIA DIMENSIONS', '19407089810');
INSERT INTO equipo (id, cliente_id, nombre_equipo, marca, modelo, numero_serie) VALUES (14, 13, 'MASTOGRAFO DIGITAL', 'HOLOGIC', 'SELENIA DIMENSIONS', '28411084228');
INSERT INTO equipo (id, cliente_id, nombre_equipo, marca, modelo, numero_serie) VALUES (15, 14, 'MASTOGRAFO DIGITAL', 'HOLOGIC', 'SELENIA DIMENSIONS', '19407089797');
INSERT INTO equipo (id, cliente_id, nombre_equipo, marca, modelo, numero_serie) VALUES (16, 15, 'MASTOGRAFO DIGITAL', 'HOLOGIC', 'SELENIA DIMENSIONS', '28407083608');
INSERT INTO equipo (id, cliente_id, nombre_equipo, marca, modelo, numero_serie) VALUES (17, 16, 'MASTOGRAFO DIGITAL', 'HOLOGIC', 'SELENIA DIMENSIONS', '19407089871');
INSERT INTO equipo (id, cliente_id, nombre_equipo, marca, modelo, numero_serie) VALUES (18, 17, 'MASTOGRAFO DIGITAL', 'HOLOGIC', 'SELENIA DIMENSIONS', '19407089869');
INSERT INTO equipo (id, cliente_id, nombre_equipo, marca, modelo, numero_serie) VALUES (19, 18, 'MASTOGRAFO DIGITAL', 'HOLOGIC', 'SELENIA DIMENSIONS', '19407089867');
INSERT INTO equipo (id, cliente_id, nombre_equipo, marca, modelo, numero_serie) VALUES (20, 19, 'MASTOGRAFO DIGITAL', 'HOLOGIC', 'SELENIA DIMENSIONS', '28411083949');
INSERT INTO equipo (id, cliente_id, nombre_equipo, marca, modelo, numero_serie) VALUES (21, 20, 'MASTOGRAFO DIGITAL', 'HOLOGIC', 'SELENIA DIMENSIONS', '19408116859');
INSERT INTO equipo (id, cliente_id, nombre_equipo, marca, modelo, numero_serie) VALUES (22, 21, 'MASTOGRAFO DIGITAL', 'HOLOGIC', 'SELENIA DIMENSIONS', '28403137697');
INSERT INTO equipo (id, cliente_id, nombre_equipo, marca, modelo, numero_serie) VALUES (23, 22, 'MASTOGRAFO DIGITAL', 'HOLOGIC', 'SELENIA DIMENSIONS', '28403137705');
INSERT INTO equipo (id, cliente_id, nombre_equipo, marca, modelo, numero_serie) VALUES (24, 23, 'MASTOGRAFO DIGITAL', 'HOLOGIC', 'SELENIA DIMENSIONS', '29402148023');
INSERT INTO equipo (id, cliente_id, nombre_equipo, marca, modelo, numero_serie) VALUES (25, 24, 'MASTOGRAFO DIGITAL', 'HOLOGIC', 'LORAD M-IV', '18009127027');
INSERT INTO equipo (id, cliente_id, nombre_equipo, marca, modelo, numero_serie) VALUES (26, 3, 'MASTOGRAFO DIGITAL', 'HOLOGIC', 'LORAD SELENIA', '28401105419');
INSERT INTO equipo (id, cliente_id, nombre_equipo, marca, modelo, numero_serie) VALUES (27, 25, 'MASTOGRAFO DIGITAL', 'PHILIPS', 'MICRODOSE SI L50', '160110-10');
INSERT INTO equipo (id, cliente_id, nombre_equipo, marca, modelo, numero_serie) VALUES (28, 26, 'MASTOGRAFO DIGITAL', 'PHILIPS', 'MICRODOSE SI L50', '170016-10');
INSERT INTO equipo (id, cliente_id, nombre_equipo, marca, modelo, numero_serie) VALUES (29, 27, 'MASTOGRAFO DIGITAL', 'PHILIPS', 'MICRODOSE SI L50', '160112-10');
INSERT INTO equipo (id, cliente_id, nombre_equipo, marca, modelo, numero_serie) VALUES (30, 28, 'MASTOGRAFO DIGITAL', 'PHILIPS', 'MICRODOSE SI L50', '170018-10');
INSERT INTO equipo (id, cliente_id, nombre_equipo, marca, modelo, numero_serie) VALUES (31, 29, 'MASTOGRAFO DIGITAL', 'PHILIPS', 'MICRODOSE SI L50', '170013-10');
INSERT INTO equipo (id, cliente_id, nombre_equipo, marca, modelo, numero_serie) VALUES (32, 30, 'MASTOGRAFO DIGITAL', 'PHILIPS', 'MICRO DOSE', '170014-10');
INSERT INTO equipo (id, cliente_id, nombre_equipo, marca, modelo, numero_serie) VALUES (33, 31, 'MASTOGRAFO DIGITAL', 'PHILIPS', 'MICRODOSE SI L50', '160104-10');
INSERT INTO equipo (id, cliente_id, nombre_equipo, marca, modelo, numero_serie) VALUES (34, 32, 'MASTOGRAFO DIGITAL', 'PHILIPS', 'MICRODOSE SI L50', '180007-10');
INSERT INTO equipo (id, cliente_id, nombre_equipo, marca, modelo, numero_serie) VALUES (35, 33, 'MASTOGRAFO DIGITAL', 'PHILIPS', 'MICRODOSE (L30)', '800405-10');
INSERT INTO equipo (id, cliente_id, nombre_equipo, marca, modelo, numero_serie) VALUES (36, 34, 'MASTOGRAFO DIGITAL', 'PHILIPS', 'MICRODOSE', '900114-10');
INSERT INTO equipo (id, cliente_id, nombre_equipo, marca, modelo, numero_serie) VALUES (37, 35, 'UNIDAD PARA TOMOGRAFIA COMPUTARIZADA MULTICORTES DE 16 O 20 CORTES', 'PHILIPS', 'BRILLIANCE CT', '50226');
INSERT INTO equipo (id, cliente_id, nombre_equipo, marca, modelo, numero_serie) VALUES (38, 36, 'UNIDAD PARA TOMOGRAFIA COMPUTARIZADA MULTICORTES DE 16 O 20 CORTES', 'SIEMENS', 'SOMATOM EMOTION 16', '69768');
INSERT INTO equipo (id, cliente_id, nombre_equipo, marca, modelo, numero_serie) VALUES (39, 37, 'UNIDAD PARA TOMOGRAFIA COMPUTARIZADA MULTICORTES DE 16 O 20 CORTES', 'SIEMENS', 'SOMATOM SCOPE', '132001');
INSERT INTO equipo (id, cliente_id, nombre_equipo, marca, modelo, numero_serie) VALUES (40, 31, 'UNIDAD PARA TOMOGRAFIA COMPUTARIZADA MULTICORTES DE 16 O 20 CORTES', 'SIEMENS', 'SOMATOM EMOTION 16', '39341');
INSERT INTO equipo (id, cliente_id, nombre_equipo, marca, modelo, numero_serie) VALUES (41, 38, 'UNIDAD PARA TOMOGRAFIA COMPUTARIZADA MULTICORTES DE 16 O 20 CORTES', 'SIEMENS', 'SOMATOME EMOTION', '78879');
INSERT INTO equipo (id, cliente_id, nombre_equipo, marca, modelo, numero_serie) VALUES (42, 5, 'UNIDAD PARA TOMOGRAFIA COMPUTARIZADA MULTICORTES DE 16 O 20 CORTES', 'SIEMENS', 'SOMATOM EMOTION ', '43933');
INSERT INTO equipo (id, cliente_id, nombre_equipo, marca, modelo, numero_serie) VALUES (43, 39, 'UNIDAD PARA TOMOGRAFIA COMPUTARIZADA MULTICORTES DE 16 O 20 CORTES', 'SIEMENS', 'SOMATON SCOPE', '92885');
INSERT INTO equipo (id, cliente_id, nombre_equipo, marca, modelo, numero_serie) VALUES (44, 40, 'UNIDAD PARA TOMOGRAFIA COMPUTARIZADA MULTICORTES DE 16 O 20 CORTES', 'SIEMENS', 'SOMATOM SCOPE', '92886');
INSERT INTO equipo (id, cliente_id, nombre_equipo, marca, modelo, numero_serie) VALUES (45, 41, 'UNIDAD PARA TOMOGRAFIA COMPUTARIZADA MULTICORTES DE 16 O 20 CORTES', 'SIEMENS', 'SOMATOM EMOTION 16', '39606');
INSERT INTO equipo (id, cliente_id, nombre_equipo, marca, modelo, numero_serie) VALUES (46, 42, 'UNIDAD PARA TOMOGRAFIA COMPUTARIZADA MULTICORTES DE 32 O 40 CORTES', 'SIEMENS', 'SOMATOM SENSATION 40', '57293');
INSERT INTO equipo (id, cliente_id, nombre_equipo, marca, modelo, numero_serie) VALUES (47, 43, 'UNIDAD PARA TOMOGRAFIA COMPUTARIZADA MULTICORTES DE 64 CORTES', 'NEUSOFT', 'NEUVIZ 64', 'N64IN200399E');
INSERT INTO equipo (id, cliente_id, nombre_equipo, marca, modelo, numero_serie) VALUES (48, 44, 'UNIDAD PARA TOMOGRAFIA COMPUTARIZADA MULTICORTES DE 64 CORTES', 'PHILIPS', 'BRILLIANCE 64', '10780');
INSERT INTO equipo (id, cliente_id, nombre_equipo, marca, modelo, numero_serie) VALUES (49, 45, 'UNIDAD PARA TOMOGRAFIA COMPUTARIZADA MULTICORTES DE 64 CORTES', 'PHILIPS', 'BRILLANCE CT64', '10108');
INSERT INTO equipo (id, cliente_id, nombre_equipo, marca, modelo, numero_serie) VALUES (50, 46, 'UNIDAD PARA TOMOGRAFIA COMPUTARIZADA MULTICORTES DE 64 CORTES', 'SIEMENS', 'SOMATOM DEFINITION AS', '96311');
INSERT INTO equipo (id, cliente_id, nombre_equipo, marca, modelo, numero_serie) VALUES (51, 47, 'INYECTOR DE MEDIO DE CONTRASTE PARA RESONANCIA MAGNETICA', 'BAYER MEDICAL CARE INC.', 'SPECTRIS', '33266');
INSERT INTO equipo (id, cliente_id, nombre_equipo, marca, modelo, numero_serie) VALUES (52, 48, 'INYECTOR DE MEDIO DE CONTRASTE PARA RESONANCIA MAGNETICA', 'BAYER MEDICAL CARE INC.', 'MEDRAD SPECTRIS SOLARIS EP', '60764679220590');
INSERT INTO equipo (id, cliente_id, nombre_equipo, marca, modelo, numero_serie) VALUES (53, 49, 'INYECTOR DE MEDIO DE CONTRASTE PARA RESONANCIA MAGNETICA', 'BAYER MEDICAL CARE INC.', 'SPECTRIS SOLARIS EP', '90100400000000');
INSERT INTO equipo (id, cliente_id, nombre_equipo, marca, modelo, numero_serie) VALUES (54, 42, 'INYECTOR DE MEDIO DE CONTRASTE PARA RESONANCIA MAGNETICA', 'BAYER MEDICAL CARE INC.', 'SPECTRIS SOLARIS EP MR INJECTION SYSTEM', '3012012 439260');
INSERT INTO equipo (id, cliente_id, nombre_equipo, marca, modelo, numero_serie) VALUES (55, 50, 'INYECTOR DE MEDIO DE CONTRASTE PARA RESONANCIA MAGNETICA', 'GUERBET', 'OPTISTAR ELITE', 'C0923D371G');
INSERT INTO equipo (id, cliente_id, nombre_equipo, marca, modelo, numero_serie) VALUES (56, 37, 'INYECTOR DE MEDIO DE CONTRASTE PARA RESONANCIA MAGNETICA', 'GUERBET', 'OPTISTAR ELITE', 'C0320D362G');
INSERT INTO equipo (id, cliente_id, nombre_equipo, marca, modelo, numero_serie) VALUES (57, 51, 'INYECTOR DE MEDIO DE CONTRASTE PARA RESONANCIA MAGNETICA', 'GUERBET', 'OPTISTAR ELITE', 'C0422D127G');
INSERT INTO equipo (id, cliente_id, nombre_equipo, marca, modelo, numero_serie) VALUES (58, 52, 'INYECTOR DE MEDIO DE CONTRASTE PARA RESONANCIA MAGNETICA', 'GUERBET', 'OPTISTAR ELITE', 'C0320D350G');
INSERT INTO equipo (id, cliente_id, nombre_equipo, marca, modelo, numero_serie) VALUES (59, 53, 'INYECTOR DE MEDIO DE CONTRASTE PARA RESONANCIA MAGNETICA', 'LIEBEL-FLARSHEIM COMPANY LLC', 'OPTISTAR ELITE', 'C0320D352G');
INSERT INTO equipo (id, cliente_id, nombre_equipo, marca, modelo, numero_serie) VALUES (60, 54, 'INYECTOR DE MEDIO DE CONTRASTE PARA RESONANCIA MAGNETICA', 'MEDRAD', 'SPECTRO SOLARIS EP', '3012012 45883');
INSERT INTO equipo (id, cliente_id, nombre_equipo, marca, modelo, numero_serie) VALUES (61, 55, 'INYECTOR DE MEDIO DE CONTRASTE PARA RESONANCIA MAGNETICA', 'MEDTRON', 'ACCUTRON MR', '880023150');
INSERT INTO equipo (id, cliente_id, nombre_equipo, marca, modelo, numero_serie) VALUES (62, 56, 'INYECTOR DE MEDIO DE CONTRASTE PARA RESONANCIA MAGNETICA', 'OPTISTAR', 'ELITE', 'C0318D279G');
INSERT INTO equipo (id, cliente_id, nombre_equipo, marca, modelo, numero_serie) VALUES (63, 57, 'INYECTOR DE MEDIO DE CONTRASTE PARA RESONANCIA MAGNETICA', 'OPTISTAR ', 'ELITE', 'C0424D77056');
INSERT INTO equipo (id, cliente_id, nombre_equipo, marca, modelo, numero_serie) VALUES (64, 38, 'INYECTOR DE MEDIO DE CONTRASTE PARA TOMOGRAFIA COMPUTARIZADA DE DOBLE JERINGA', 'BAYER MEDICAL CARE INC.', 'STELLANT', '301422661292');
INSERT INTO equipo (id, cliente_id, nombre_equipo, marca, modelo, numero_serie) VALUES (65, 2, 'INYECTOR DE MEDIO DE CONTRASTE PARA TOMOGRAFIA COMPUTARIZADA DE DOBLE JERINGA', 'BAYER MEDICAL CARE INC.', 'MARK V PROVIS', '110764/35059');
INSERT INTO equipo (id, cliente_id, nombre_equipo, marca, modelo, numero_serie) VALUES (66, 40, 'INYECTOR DE MEDIO DE CONTRASTE PARA TOMOGRAFIA COMPUTARIZADA DE DOBLE JERINGA', 'BAYER MEDICAL CARE INC.', 'STELLANT', '60764865 200143');
INSERT INTO equipo (id, cliente_id, nombre_equipo, marca, modelo, numero_serie) VALUES (67, 54, 'INYECTOR DE MEDIO DE CONTRASTE PARA TOMOGRAFIA COMPUTARIZADA DE DOBLE JERINGA', 'BAYER MEDICAL CARE INC.', 'MARK V PROVIS', '109841');
INSERT INTO equipo (id, cliente_id, nombre_equipo, marca, modelo, numero_serie) VALUES (68, 54, 'INYECTOR DE MEDIO DE CONTRASTE PARA TOMOGRAFIA COMPUTARIZADA DE DOBLE JERINGA', 'BAYER MEDICAL CARE INC.', 'STELLANT', '3014226 42261');
INSERT INTO equipo (id, cliente_id, nombre_equipo, marca, modelo, numero_serie) VALUES (69, 58, 'INYECTOR DE MEDIO DE CONTRASTE PARA TOMOGRAFIA COMPUTARIZADA DE DOBLE JERINGA', 'BAYER MEDICAL CARE INC.', 'STELLANT SCT-210', '60726726 202021');
INSERT INTO equipo (id, cliente_id, nombre_equipo, marca, modelo, numero_serie) VALUES (70, 48, 'INYECTOR DE MEDIO DE CONTRASTE PARA TOMOGRAFIA COMPUTARIZADA DE DOBLE JERINGA', 'BAYER MEDICAL CARE INC.', 'MEDRAD STELLANT', '60764873205955');
INSERT INTO equipo (id, cliente_id, nombre_equipo, marca, modelo, numero_serie) VALUES (71, 49, 'INYECTOR DE MEDIO DE CONTRASTE PARA TOMOGRAFIA COMPUTARIZADA DE DOBLE JERINGA', 'BAYER MEDICAL CARE INC.', 'STELLANT', '3014226 43089');
INSERT INTO equipo (id, cliente_id, nombre_equipo, marca, modelo, numero_serie) VALUES (72, 59, 'INYECTOR DE MEDIO DE CONTRASTE PARA TOMOGRAFIA COMPUTARIZADA DE DOBLE JERINGA', 'BAYER MEDICAL CARE INC.', 'VISTRON CT', '403002156A 59258');
INSERT INTO equipo (id, cliente_id, nombre_equipo, marca, modelo, numero_serie) VALUES (73, 57, 'INYECTOR DE MEDIO DE CONTRASTE PARA TOMOGRAFIA COMPUTARIZADA DE DOBLE JERINGA', 'BAYER MEDICAL CARE INC.', 'DC045D', '87474275D87677');
INSERT INTO equipo (id, cliente_id, nombre_equipo, marca, modelo, numero_serie) VALUES (74, 60, 'INYECTOR DE MEDIO DE CONTRASTE PARA TOMOGRAFIA COMPUTARIZADA DE DOBLE JERINGA', 'BAYER MEDICAL CARE INC.', 'STELLANT D', '32015');
INSERT INTO equipo (id, cliente_id, nombre_equipo, marca, modelo, numero_serie) VALUES (75, 61, 'INYECTOR DE MEDIO DE CONTRASTE PARA TOMOGRAFIA COMPUTARIZADA DE DOBLE JERINGA', 'GUERBET', 'OPTIVANTAGE', '0175E2006');
INSERT INTO equipo (id, cliente_id, nombre_equipo, marca, modelo, numero_serie) VALUES (76, 62, 'INYECTOR DE MEDIO DE CONTRASTE PARA TOMOGRAFIA COMPUTARIZADA DE DOBLE JERINGA', 'GUERBET', 'OPTIVANTAGE', 'C0124B926G');
INSERT INTO equipo (id, cliente_id, nombre_equipo, marca, modelo, numero_serie) VALUES (77, 45, 'INYECTOR DE MEDIO DE CONTRASTE PARA TOMOGRAFIA COMPUTARIZADA DE DOBLE JERINGA', 'GUERBET', 'OPTIVANTAGE', 'C0822B775G');
INSERT INTO equipo (id, cliente_id, nombre_equipo, marca, modelo, numero_serie) VALUES (78, 63, 'INYECTOR DE MEDIO DE CONTRASTE PARA TOMOGRAFIA COMPUTARIZADA DE DOBLE JERINGA', 'GUERBET', 'OPTIVANTAGE', 'C1021B722G');
INSERT INTO equipo (id, cliente_id, nombre_equipo, marca, modelo, numero_serie) VALUES (79, 52, 'INYECTOR DE MEDIO DE CONTRASTE PARA TOMOGRAFIA COMPUTARIZADA DE DOBLE JERINGA', 'GUERBET', 'OPTIVANTAGE', 'C0721B934G');
INSERT INTO equipo (id, cliente_id, nombre_equipo, marca, modelo, numero_serie) VALUES (80, 64, 'INYECTOR DE MEDIO DE CONTRASTE PARA TOMOGRAFIA COMPUTARIZADA DE DOBLE JERINGA', 'ILUMENA ', 'NEO', 'C0723C961G');
INSERT INTO equipo (id, cliente_id, nombre_equipo, marca, modelo, numero_serie) VALUES (81, 55, 'INYECTOR DE MEDIO DE CONTRASTE PARA TOMOGRAFIA COMPUTARIZADA DE DOBLE JERINGA', 'LF', 'OPTIVANTAGE', 'C0523B513G');
INSERT INTO equipo (id, cliente_id, nombre_equipo, marca, modelo, numero_serie) VALUES (82, 4, 'INYECTOR DE MEDIO DE CONTRASTE PARA TOMOGRAFIA COMPUTARIZADA DE DOBLE JERINGA', 'MALLINCKRODT', '844100 H', 'C0115B556R');
INSERT INTO equipo (id, cliente_id, nombre_equipo, marca, modelo, numero_serie) VALUES (83, 54, 'INYECTOR DE MEDIO DE CONTRASTE PARA TOMOGRAFIA COMPUTARIZADA DE DOBLE JERINGA', 'MEDRAD', 'STELLANT DUAL', '36189');
INSERT INTO equipo (id, cliente_id, nombre_equipo, marca, modelo, numero_serie) VALUES (84, 65, 'INYECTOR DE MEDIO DE CONTRASTE PARA TOMOGRAFIA COMPUTARIZADA DE DOBLE JERINGA', 'MEDRAD', 'STELANT', '3014226-36315');
INSERT INTO equipo (id, cliente_id, nombre_equipo, marca, modelo, numero_serie) VALUES (85, 66, 'INYECTOR DE MEDIO DE CONTRASTE PARA TOMOGRAFIA COMPUTARIZADA DE DOBLE JERINGA', 'NEMOTO', 'DUAL SHOT ALPHA7', 'QCUS 3001 G');
INSERT INTO equipo (id, cliente_id, nombre_equipo, marca, modelo, numero_serie) VALUES (86, 67, 'INYECTOR DE MEDIO DE CONTRASTE PARA TOMOGRAFIA COMPUTARIZADA DE DOBLE JERINGA', 'NEMOTO', 'DUAL SHOT ALPHA 7', 'QCBS 3071 G');
INSERT INTO equipo (id, cliente_id, nombre_equipo, marca, modelo, numero_serie) VALUES (87, 23, 'INYECTOR DE MEDIO DE CONTRASTE PARA TOMOGRAFIA COMPUTARIZADA DE DOBLE JERINGA', 'NEMOTO', 'DUAL SHOT ALPHA 7', 'QCBS3038G');
INSERT INTO equipo (id, cliente_id, nombre_equipo, marca, modelo, numero_serie) VALUES (88, 68, 'INYECTOR DE MEDIO DE CONTRASTE PARA TOMOGRAFIA COMPUTARIZADA DE DOBLE JERINGA', 'OPTIVANTAGE', '846700 B', 'C1121B860G');
INSERT INTO equipo (id, cliente_id, nombre_equipo, marca, modelo, numero_serie) VALUES (89, 4, 'INYECTOR DE MEDIO DE CONTRASTE PARA TOMOGRAFIA COMPUTARIZADA PARA APLICACIONES GENERALES', 'ACIST CVI', 'INJECTOR HEAD', '30020239');
INSERT INTO equipo (id, cliente_id, nombre_equipo, marca, modelo, numero_serie) VALUES (90, 47, 'INYECTOR DE MEDIO DE CONTRASTE PARA TOMOGRAFIA COMPUTARIZADA PARA APLICACIONES GENERALES', 'BAYER MEDICAL CARE INC.', ' MARK V PROVIS PPD', '101879');
INSERT INTO equipo (id, cliente_id, nombre_equipo, marca, modelo, numero_serie) VALUES (91, 47, 'INYECTOR DE MEDIO DE CONTRASTE PARA TOMOGRAFIA COMPUTARIZADA PARA APLICACIONES GENERALES', 'BAYER MEDICAL CARE INC.', 'VISTRON CT', '54727');
INSERT INTO equipo (id, cliente_id, nombre_equipo, marca, modelo, numero_serie) VALUES (92, 69, 'INYECTOR DE MEDIO DE CONTRASTE PARA TOMOGRAFIA COMPUTARIZADA PARA APLICACIONES GENERALES', 'BAYER MEDICAL CARE INC.', 'STELLANT', '301423000000');
INSERT INTO equipo (id, cliente_id, nombre_equipo, marca, modelo, numero_serie) VALUES (93, 37, 'INYECTOR DE MEDIO DE CONTRASTE PARA TOMOGRAFIA COMPUTARIZADA PARA APLICACIONES GENERALES', 'BAYER MEDICAL CARE INC.', 'MEDRAD STELLANT ', '80764873 206607');
INSERT INTO equipo (id, cliente_id, nombre_equipo, marca, modelo, numero_serie) VALUES (94, 70, 'INYECTOR DE MEDIO DE CONTRASTE PARA TOMOGRAFIA COMPUTARIZADA PARA APLICACIONES GENERALES', 'BAYER MEDICAL CARE INC.', 'STELLANT D', '107447/ 32274');
INSERT INTO equipo (id, cliente_id, nombre_equipo, marca, modelo, numero_serie) VALUES (95, 71, 'INYECTOR DE MEDIO DE CONTRASTE PARA TOMOGRAFIA COMPUTARIZADA PARA APLICACIONES GENERALES', 'BAYER MEDICAL CARE INC.', 'ACP', '60764865 200285');
INSERT INTO equipo (id, cliente_id, nombre_equipo, marca, modelo, numero_serie) VALUES (96, 56, 'INYECTOR DE MEDIO DE CONTRASTE PARA TOMOGRAFIA COMPUTARIZADA PARA APLICACIONES GENERALES', 'BAYER MEDICAL CARE INC.', 'VHU 600', '51749');
INSERT INTO equipo (id, cliente_id, nombre_equipo, marca, modelo, numero_serie) VALUES (97, 45, 'INYECTOR DE MEDIO DE CONTRASTE PARA TOMOGRAFIA COMPUTARIZADA PARA APLICACIONES GENERALES', 'BAYER MEDICAL CARE INC.', 'MARK 7 ARTERIAN', '86410060 112918');
INSERT INTO equipo (id, cliente_id, nombre_equipo, marca, modelo, numero_serie) VALUES (98, 42, 'INYECTOR DE MEDIO DE CONTRASTE PARA TOMOGRAFIA COMPUTARIZADA PARA APLICACIONES GENERALES', 'BAYER MEDICAL CARE INC.', 'STELLANT FLEX CT INJECTION SYSTEM', '105680');
INSERT INTO equipo (id, cliente_id, nombre_equipo, marca, modelo, numero_serie) VALUES (99, 50, 'INYECTOR DE MEDIO DE CONTRASTE PARA TOMOGRAFIA COMPUTARIZADA PARA APLICACIONES GENERALES', 'GUERBET', 'ILLUMENA NEO', 'C10119C111G');
INSERT INTO equipo (id, cliente_id, nombre_equipo, marca, modelo, numero_serie) VALUES (100, 51, 'INYECTOR DE MEDIO DE CONTRASTE PARA TOMOGRAFIA COMPUTARIZADA PARA APLICACIONES GENERALES', 'GUERBET', 'OPTIVANTAGE', 'C1121B859G');
INSERT INTO equipo (id, cliente_id, nombre_equipo, marca, modelo, numero_serie) VALUES (101, 51, 'INYECTOR DE MEDIO DE CONTRASTE PARA TOMOGRAFIA COMPUTARIZADA PARA APLICACIONES GENERALES', 'GUERBET', 'ILLUMENA NEO', 'C119C117G');
INSERT INTO equipo (id, cliente_id, nombre_equipo, marca, modelo, numero_serie) VALUES (102, 48, 'INYECTOR DE MEDIO DE CONTRASTE PARA TOMOGRAFIA COMPUTARIZADA PARA APLICACIONES GENERALES', 'LIEBEL-FLARSHEIM COMPANY LLC', 'ILLUMENA NÉO', 'C1019C077G');
INSERT INTO equipo (id, cliente_id, nombre_equipo, marca, modelo, numero_serie) VALUES (103, 72, 'INYECTOR DE MEDIO DE CONTRASTE PARA TOMOGRAFIA COMPUTARIZADA PARA APLICACIONES GENERALES', 'MALLINCKRODT', 'OPTIVANTAGE DH', 'C0115B560R');
INSERT INTO equipo (id, cliente_id, nombre_equipo, marca, modelo, numero_serie) VALUES (104, 42, 'INYECTOR DE MEDIO DE CONTRASTE PARA TOMOGRAFIA COMPUTARIZADA PARA APLICACIONES GENERALES', 'MALLINCKRODT ', 'OPTIVANTAGE DH CT INJECTOR SYSTEM', 'CL1108B520');
INSERT INTO equipo (id, cliente_id, nombre_equipo, marca, modelo, numero_serie) VALUES (105, 73, 'INYECTOR DE MEDIO DE CONTRASTE PARA TOMOGRAFIA COMPUTARIZADA PARA APLICACIONES GENERALES', 'ULRICH MEDICAL', 'CT MOTION', 'CTM1510792');
INSERT INTO equipo (id, cliente_id, nombre_equipo, marca, modelo, numero_serie) VALUES (106, 74, 'INYECTOR DE MEDIO DE CONTRASTE PARA TOMOGRAFIA COMPUTARIZADA PARA APLICACIONES GENERALES', 'ULRICH MEDICAL', 'CT MOTION', 'CTM1922213');
INSERT INTO equipo (id, cliente_id, nombre_equipo, marca, modelo, numero_serie) VALUES (107, 75, 'SISTEMA DE DIGITALIZACION DE IMAGENES (RADIOGRAFIA COMPUTARIZADA) DE BAJO DESEMPEÑO PARA MASTOGRAFIA Y RAYOS X DE PROPOSITO GENERAL ', 'CARESTREAM ', 'DIRECTVIEW CLASSIC CR', 'K5241-1183');
INSERT INTO equipo (id, cliente_id, nombre_equipo, marca, modelo, numero_serie) VALUES (108, 76, 'SISTEMA DE DIGITALIZACION DE IMAGENES (RADIOGRAFIA COMPUTARIZADA) DE BAJO DESEMPEÑO PARA MASTOGRAFIA Y RAYOS X DE PROPOSITO GENERAL ', 'CARESTREAM ', 'DIRECTVIEW CLASSIC CR', 'K5240-8336');

-- ============================================================
-- Sincronización de Secuencias (Crucial para evitar PK collisions)
-- ============================================================
SELECT setval(pg_get_serial_sequence('cliente', 'id'), coalesce(max(id), 1), max(id) IS NOT null) FROM cliente;
SELECT setval(pg_get_serial_sequence('equipo', 'id'), coalesce(max(id), 1), max(id) IS NOT null) FROM equipo;